### ISSUE TITLE
I cant open

### ISSUE THREAD

**Issue by TheFilipGames** [benvanik/xenia#1079]
Hi, I cant open xenia emulator, i double click on it at nothing is doing, please help
I have geforce 1050ti and Intel core 2 quad Q9550 2.83Ghz.
I have windows 10.

**Comment by Razzile** [comment]
your cpu is too old to support xenia. you need to have an AVX compatible cpu (sandy bridge+)

**Comment by TheFilipGames** [comment]
Ok thanks

**Comment by apk85** [comment]
I have an Intel Core i7 and it doesn't support avx. 😞

**Comment by Razzile** [comment]
@apk85 as far as I know, only the 1st generation of the 'Core i' lineup doesn't support AVX so if you want to use xenia you could upgrade to any 2nd gen or higher core i3/i5/i7/i9. Please note that for whatever reason intel refuses to let pentiums have AVX support

**Comment by mirh** [comment]
Market segmentation, otherwise they'd be identical to an i3 (well, at least before Coffee Lake). 
Anyway, if anybody was interested into fixing this, last time I checked the first actual *illegal* instruction you meet on launch was a pesky vmovsd somewhere around the time of processor execute in XThread.
