### ISSUE TITLE
XAudio2_9.dll

### ISSUE THREAD

**Issue by victorheld** [benvanik/xenia#267]
Whenever I open Xenia i get the error that XAudio2_9.dll is missing from my computer
![screenshot 1](https://cloud.githubusercontent.com/assets/1809198/8261352/13382acc-16ca-11e5-98d3-3b6b31009345.png)

**Comment by Evolution0** [comment]
Install directx 9 and see if you still get the error.

**Comment by victorheld** [comment]
After installing DirectX 9 the problem still persists

**Comment by Nezarn** [comment]
Try updating DirectX with this: https://www.microsoft.com/en-US/Download/details.aspx?id=35

**Comment by Razzile** [comment]
I had this problem. Go into xenia settings in visual studio and change the target for all projects to windows 8.1 from windows 10.

![Image](http://i.imgur.com/vc1bggg.jpg)

If like me, you couldn't select windows 8.1, uninstall the windows 10 SDK from your machine, reboot and try again.

The problem is caused by building xenia with the windows 10 sdk, so it links to windows 10 DLLs such as XAudio2_9.dll which doesn't exist on windows 8.1 or below.

**Comment by victorheld** [comment]
Thanks [Razzile](https://github.com/Razzile) it is now fixed.
