### ISSUE TITLE
Replace BeaEngine use in mmio_handler.cc with custom x64 mov decoder.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#358]
BeaEngine is currently only used to see if the instruction making an access violation is a mov performing a load or store and getting the registers/immediate values involved. For the small set of mov's this could be done much faster and without the BeaEngine dependency.

**Comment by hlide** [comment]
Intriguing. What is the purpose to need such information when an access violation occurs? debugging purpose or some magic stuff?

**Comment by benvanik** [comment]
This is used to handle non-constant hardware register reads/writes. In most cases registers can be handled at JIT-time by detecting constant addresses (done [here](https://github.com/benvanik/xenia/blob/master/src/xenia/cpu/backend/x64/x64_sequences.cc#L2001)), but there are cases where they are dynamic (lots of audio code that calculates register number based on the audio channel assigned to it earlier in the program, etc) that still need to be handled. I then NOACCESS the pages that registers are in and an exception handler looks for loads/stores to those addresses ([here](https://github.com/benvanik/xenia/blob/master/src/xenia/cpu/mmio_handler.cc#L235)), performs the load/store, and then resumes execution after the original load/store. It means that these kinds of dynamic accesses can be handled without the need to check every memory load/store, which is pretty sweet. Usually only <10 are done per frame, so even though it's not cheap it's at least infrequent.

**Comment by hlide** [comment]
I see. It reminds me of Exophase's GBA emulator where memory accesses were headache to handle (especially those regarding MMIO) : Dynamically patched memory handlers and Delayed modified block handling. No exception (too expensive), but the principle is almost same.

**Comment by benvanik** [comment]
Yeah, I'd like to go patch up the code that does the accesses once it's known that is what it's doing (as in most cases it's just a few locations that do the reads/writes). Having just a few exceptions per run in the beginning and none in the steady state would be nice :)

**Comment by skmp** [comment]
Just to share my two cents here, you might find it useful to also have some "block-rewrite" logic apart from just opcode patching -- I've been doing this for quite some years and it can become a headache with graph-compilation and making sure there's enough bytes to do the patches. Also, instead of decoding instructions, it might be worthwhile to keep a reverse lookup tree with the block native addresses, and look the code address to find the meta-information. Trees can be extended to work for non-overlapping ranges with the same LogN lookup time (< && > are obv. == when addr in block)
