### ISSUE TITLE
Spotty GLEW feature detection

### ISSUE THREAD

**Issue by sephiroth99** [benvanik/xenia#359]
As indicated by the TODO in https://github.com/benvanik/xenia/blob/master/src/xenia/ui/gl/gl_context.cc#L268 some feature are not properly discovered. See also previous issue #342.

This issue is to track its investigation.

**Comment by sephiroth99** [comment]
After a quick look at GLEW code, it seems that it happens, in the specific case of the TODO, when GLEW is in Experimental mode. When it is disabled, the check occurs correctly.

This happens because in experimental mode, the GL_EXTENSION string is not used by GLEW to detect features, and the GLEW_ARB_fragment_coord_conventions feature is only searched in the extension string, unlike some other extensions that are searched with glewGetProcAddress when in experimental mode.

So to fix it, experimental mode could be disabled, but I don't know why it was in the first place. Thoughts?

**Comment by sephiroth99** [comment]
In the case of the issue (GL_ARB_bindless_texture), my guess is that the feature was not in the GL_EXTENSIONS string, but because of experimental mode, the driver had a buggy version that glewGetProcAddress found.

**Comment by benvanik** [comment]
Wow, good find!

**Comment by benvanik** [comment]
Looks like I was setting this because in CreateShared the new context returns an empty string for the extension query in GLEW, which then causes all the extensions to fail to load from that context. I have no clue why this happens, and must have given up and just turned on the flag out of frustration. Will see if I can figure out it.
