### ISSUE TITLE
Investigate save state feasibility.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#40]
Would be great to support. Seems difficult.

### CPU
For saving need to be able to suspend all threads and capture all thread state. This is difficult in a deep JIT, as if PPC registers are kept in host registers and single PPC instructions can be many IR ops that cannot be divided.

Having synchronization points that check for save state markers and suspend the threads could make it work. A 'save state pending' check on function calls could work in most cases, though all branches may need it too. Yuck.

### GPU
A state manager would need to retain all objects (textures/buffers/etc) so that they can be read back, saved, and later recreated.

### Kernel
All thread primitives (wait/etc) would need to support alerting so that they could be woken and later waited. Any kernel state (object table/etc) would need to be fully serializable. Any host pointers stored in guest code would need to be rewritten (like locks/etc).

**Comment by raven02** [comment]
Not too sure if @unknownbrackets interest , he implemented savestate support for PPSSPP previously

**Comment by unknownbrackets** [comment]
In PPSSPP we only do savestate checks once per frame (and also when trapped in the debugger.)  This works great.  No need to do it at the function level - KISS.  One frame lag for a savestate is mostly fine, unless you're already paused anyway.

We also completely avoid host pointers, using registered ids.  Then again, we also do all "threading" manually since the PSP is single core, which makes that easier.

IMHO you should except real host thread primitives to already potentially alarm at unexpected times.

The trickiest (and only quasi handled) issue in PPSSPP with savestates is callbacks.  When an HLE function is passed a callback that it then calls, things can get tricky if that isn't resumable.  For this reason we never allow the cpu runloop to be entered from within a syscall.  Not sure if xenia needs to worry about these issues.

-[Unknown]

**Comment by raven02** [comment]
Thanks for the commit . @unknownbrackets

**Comment by benvanik** [comment]
Dupe of the active #459
