### ISSUE TITLE
Save States

### ISSUE THREAD

**Issue by DrChat** [benvanik/xenia#459]
* Serialization of the kernel state (and by extension, all XObjects)
* Threads
 * We can reconstruct the host stack by walking the guest stack at runtime.
   * For locals (spilled registers) we could step the thread until they're guaranteed to be in sync with the PPC context.
 * In HLE Functions
   * We can't save a thread that's in a HLE function. We'll have to run the thread until it returns from the HLE function and is back in guest code.
    * If the HLE function is blocking, we'll have to save the thread anyways and just have it call the HLE function again when it's restored.

* File Format
 * Would be neat to pack the state into a .zip file, with different subfiles for different areas (ex. memory file, kernel file, graphics file, etc.)
 * At the very least we should use zlib to compress the memory before writing it into a file.

**Comment by benvanik** [comment]
Blocking host functions almost always end up in a xe::threading::Wait*. We can wrap that when calling from the kernel functions to also include a global 'saving state' event (and always call WaitMultiple/WaitAll/etc - with some tricky logic - AudioSystem does this now by adding the shutdown_event_ to wait_handles_). Then, when a save state is requested, that saving state event can be signaled to wake all waiting threads. They can then check if they are being asked to save, and back out any state they have and bubble up to the syscall. When restoring state, they'll be called back into just as normal.

This requires the wrapping/identification of the waits, probably an assert so that we don't accidentally introduce waits that have guest code on the stack, all waits handling the early-exit on saving to do whatever they need to do, and code cleanup before the waits to ensure that and side-effects happen either after the wait or can be reverted.

If we have that, we can make some assertions about other code that need to be made true:

* Everywhere we can we need to use guest allocations and guest pointers instead of host pointers. This makes the code safe to restoring as addresses will be stable (as PPC addresses don't change). As we won't be trying to restore mid-host function so long as each time a pointer is used it's translated it should always be ok.

* Any host threads that call into guest code (apu/gpu interrupts) must return to host code before we can save.

* Anywhere that can recreate state should be able to (gpu mostly does this now with a cache clear, but not sure the apu does).

* GPU may need to dictate save time - possibly on swap only - as there are waits embedded in the command buffers that will be extremely difficult to restore.

The big complication here is the potential for deadlocks/livelocks between threads in different suspend states.

**Comment by hlide** [comment]
Or using APC with "alertable" wait functions (which include a bigger set of win32 waiting functions that the one cited above).

However, in both case, I wonder how you will be able to implement the Linux and OSx versions.

**Comment by DrChat** [comment]
Some stuff we can probably get away with without saving/restoring. XMA/GPU stuff runs so quick we can probably just wait til the game supplies us with new commands.

**Comment by Margen67** [comment]
#665
