### ISSUE TITLE
Xenia DX12

### ISSUE THREAD

**Issue by SakataGintokiYT** [benvanik/xenia#490]
Too bad time for OpenGL/ glsl shaders . It's time on DX12
Rpcs3 is better now on DX12 - https://www.youtube.com/watch?v=BdXpoc49BjE

**Comment by theoldsport** [comment]
Wow rpcs3 just blew straight past Xenia in that game! Even when most PS3 games barely booted a month ago. I'm pretty sure @benvanik has plans for a Vulkan backend, so DX12 may not be worth the effort right now (especially since DX12 is exclusive to Windows 10+). Vulkan's performance would likely be on par (or possibly better) than DX12, on top of being an open standard API. We're currently just waiting for its release :)

**Comment by benvanik** [comment]
@SakataGintokiYT this is off topic and not a valid use of the issue tracker.

**Comment by illusion98** [comment]
DX12 for Xenia is now available at https://github.com/xenia-project/xenia/tree/d3d12
