### ISSUE TITLE
Parse embedded xex resources to get game info.

### ISSUE THREAD

**Issue by benvanik** [benvanik/xenia#506]
Currently all we have is media/title ID. Would be nice when saving files/titling the main window/etc to have the actual name.

**Comment by kmather73** [comment]
Well one possible quick and easy way to implement this would be to do a Title_ID lookup from http://abgx360.xecuter.com/games_by_titleid.txt      The only problem with this is that it doesn't include any XBLA games and it may not include every disc based game either, in particular I'm thinking that it will miss a lot of the J-NTSC games. 

I'll try and figure how xex work and maybe get something better in the next few days/weeks

**Comment by SonofUgly** [comment]
If you're just talking about simple stuff like this, XBLA game info are easy enough to get from the file:
Name (Region 1): 0x00000412
Name (Region 2): 0x00000512
...
0x000000912

Description (Region 1): 0x00000D12
Description (Region 2): 0x00000E12
...
0x00001212

Game Name: 0x00001692
Game Icon: 0x0000171A

Or you could read from the ArcadeInfo.xml file in them.

**Comment by jackchentwkh** [comment]
xorloser is a great coder/hacker. too bad he never release his source code. I asked him few times regarding to his reverse engineering finds of the backward compatibility on 360, but never answered.
here is a source code of older version of xextool which is not supposed to be xorloser's code. but as I remembered, xorloser did mentioned that his xextool was inspired by somebody's xextool code. maybe this is it. 

https://github.com/Intline9/i360gm/tree/master/dep/xextool_old

the tool is capable for retrieving all xex infos, including a decrypted PE which one can explore more resources including the game name/game icon, etc. hope it help.

btw, xorloser packed his xextool with upx with some tricks, so one needs to unpack it manually to get  a clear exe file for idapro to reverse. I managed to unpack the exe file, and the unpacked file works fine under winxp x86, but not working under x64 which I don't know why. maybe it's because I unpack and rebuild the import section under winxp x86. the unpacked exe can be reversed in idapro, and the hexray decompiler works with it. but seems xorloser uses many low level code tricks, it's not that easy for me to reverse it clearly even with the decompiler. if any one is interested in it, I will post the unpacked version of the xextool.

btw, free60's wiki got some error with the xex file format, especially regarding to the optional header entry data size. on the other hand the source code of the xextool should be correct.

**Comment by x1nixmzeng** [comment]
Good for contributors?

@jackchentwkh do we need the source?

**Comment by jackchentwkh** [comment]
hmm, I believe that @benvanik  already has the source of older version xextool on hand. that's how xenia can load the xex file directly. I am not sure what resource he needs from the xex which he doesn't have on hand.

**Comment by x1nixmzeng** [comment]
As we've already decrypted the XEX we just need to locale the data using our resource headers.

According to XexTool we have a resource with the same name as the TitleID. We just need to go through this format to extract the game name / icon.

Quick patch for anyone following along:

In `xex2.cc`, at the end of `xe_xex2_load`:

```cpp
  {
	  char title[9] = {0};
	  sprintf_s(title, "%08X", xex->header.execution_info.title_id);

	  for (size_t n = 0; n < xex->header.resource_info_count; n++) {
		  auto resource_info = &xex->header.resource_infos[n];

		  if (strcmp(resource_info->name, title) == 0) {
			  uint8_t* buffer = memory->TranslateVirtual(resource_info->address);	  

			  FILE* test = fopen("blah.dat", "wb");

			  fwrite(buffer, resource_info->size, 1, test);
			  fclose(test);
		  }
	  }
  }
```

**Comment by kmather73** [comment]
I finished looking at the structure of the xex files and If I could make a suggestion. According to http://www.free60.org/wiki/STFS#Metadata there is a Unicode string of the games name at 0x1691. in the Metadata 

perhaps we could add another field to the struct `xe_xex2_execution_info_t ` in `xex2_info.h` (line 255) called `title_name` or `game_name` to include a 80 byte wide unsigned char array or pointer to store the Unicode string or something like that.

```c++    
    struct xe_xex2_execution_info_t {
        uint32_t media_id;
        xe_xex2_version_t version;
        xe_xex2_version_t base_version;
        uint32_t title_id;
        uint8_t platform;
        uint8_t executable_table;
        uint8_t disc_number;
        uint8_t disc_count;
        uint32_t savegame_id;
        unsigned char* game_name;
        const uint8_t game_name_length = 80; //?? maybe less then a 80 byte long Unicode string 
    };
```

Then in `xex2.cc ` in the  `XEX_HEADER_EXECUTION_INFO` case of `xe_xex2_read_header` I think you would just need the add some code to set the string

```c++
      case XEX_HEADER_EXECUTION_INFO: {
        xe_xex2_execution_info_t* ex = &header->execution_info;
        ex->media_id = xe::load_and_swap<uint32_t>(pp + 0x00);
        ex->version.value = xe::load_and_swap<uint32_t>(pp + 0x04);
        ex->base_version.value = xe::load_and_swap<uint32_t>(pp + 0x08);
        ex->title_id = xe::load_and_swap<uint32_t>(pp + 0x0C);
        ex->platform = xe::load_and_swap<uint8_t>(pp + 0x10);
        ex->executable_table = xe::load_and_swap<uint8_t>(pp + 0x11);
        ex->disc_number = xe::load_and_swap<uint8_t>(pp + 0x12);
        ex->disc_count = xe::load_and_swap<uint8_t>(pp + 0x13);
        ex->savegame_id = xe::load_and_swap<uint32_t>(pp + 0x14);
        ex->game_name = (unsigned char *) (pp + 0x1691 - 0x354); //?? maybe do a static cast
      } break;
```

But then from this point I'm not sure if there is a need for some kind of special parsing since its a Unicode string not a ASCII string and it maybe less then 80 bytes in size. I'm not really familiar at all with Unicode so I'm not sure if we could just cast it to a std::string. Anyone familiar with Unicode in C++?

**Comment by 0xdeafcafe** [comment]
Wouldn't the string be null-terminated, so you wouldn't need to store the length?

**Comment by kmather73** [comment]
@0xdeafcafe Yes you are absolutely right it is null terminated. 

I ended up finding a [MS library](https://msdn.microsoft.com/en-us/library/dd374085%28v=vs.85%29.aspx) that will parse it to a std::wstring.

**Comment by paulsapps** [comment]
Wouldn't the wstring ctor that takes a wchar_t* and a size_t be enough?

**Comment by jackchentwkh** [comment]
+1, just  leave it there with unicode should be good enough.

**Comment by x1nixmzeng** [comment]
So my branch now supports setting the window title / icon from the XDBF resource we have in the XEX module (which is what XeXTool uses to extract the application icon).

The only problem is converting the PNG to HICON correctly :unamused: Any ideas?

https://github.com/x1nixmzeng/xenia/tree/xex-resources

**Comment by paulsapps** [comment]
Something like this http://gamedev.stackexchange.com/questions/43823/how-can-i-obtain-a-hbitmap-or-hicon-from-a-direct2d-bitmap I think you can probably get a hicon from the hbitmap

**Comment by benvanik** [comment]
Done! Thanks for the contribution!
