### ISSUE TITLE
Will Xenia be ported to iOS?

### ISSUE THREAD

**Issue by nfsvsgta** [benvanik/xenia#594]
Please do

**Comment by theoldsport** [comment]
Trying to think of something sarcastic to say

**Comment by Razzile** [comment]
Hell no.

iOS has an ancient implementation of openGL ES (not even full fat openGL) and no vulkan support so xenia's renderer will never work.
iOS also has an ARM chip but xenia only converts PPC code to x86_64 so that also prevents xenia coming to iOS.
And lastly even if a new JIT compiler was written I have doubts that the ARM chips in iOS devices are too weak to effectively run xenia. And it would take somebody far more skilled than me to port a new JIT compiler to iOS

**Comment by theoldsport** [comment]
There you have it folks- iOS is a mess... iOS is a waste... iOS is a big fat mistake.

**Comment by Margen67** [comment]
#AndroidMasterRace

**Comment by MoochMcGee** [comment]
Android Xenia isn't happening either, but okay.

**Comment by gibbed** [comment]
It's not happening, that's that.
