### ISSUE TITLE
Regression in GL4 command_processor.cc

### ISSUE THREAD

**Issue by MattKackles** [benvanik/xenia#672]
Causes several games which went ingame last year to crash.

Known affected titles:
Grand Theft Auto IV
Grand Theft Auto: Episodes From Liberty City

Callstack for GTA IV:
![callstack](https://cloud.githubusercontent.com/assets/22846547/23098388/16c07e84-f61a-11e6-8096-16169a804029.png)

**Comment by DrChat** [comment]
The GL4 backend is deprecated, and I might just outright remove it soon.

**Comment by MattKackles** [comment]
@DrChat 
The vulkan backend doesn't render anything in that game.

**Comment by Deathlock47** [comment]
@DrChat why would you want to deprecate GL4? It still runs some games Vulkan doesn't and pretty often gives a more accurate output, not to mention it's the standard API for emulators

**Comment by Margen67** [comment]
That's because the Vulkan renderer/backend within Xenia is early. As time goes on it will get better eventually becoming better than the GL4 renderer.

This may be due to not as many things being emulated, but Vulkan performs better than GL4.
Vulkan on it's own is better than OpenGL, and is more actively updated unlike OpenGL.
OpenGL is old. Just because it's been the "standard" doesn't mean it's better.

If a graphics card or driver doesn't support Vulkan it probably can't handle xenia anyway.

**Comment by gibbed** [comment]
Too general of an issue to research, need to handle this on a game to game basis.
