### ISSUE TITLE
Xenia crashes while debugging

### ISSUE THREAD

**Issue by tmccaff** [benvanik/xenia#685]
I just compiled Xenia and tried to use the command

in Command prompt I enter xenia default.xex --log_file=output.log

And Xenia crashes. I am using Windows 10.

**Comment by Margen67** [comment]
Xenia is crashing because it's trying to load a file that doesn't exist.
That would only work if xenia.exe was in the same directory as default.xex.

Also launch parameters need to be put before the xex and the software needs to be in quotation marks.
So unless the xex is in the same folder as xenia you need to change those launch parameters to
`xenia --log_file=output.log "Drive:\gamefolder\default.xex"`
The log file will still be made in the same directory so if you don't want it to do that you will need to add a path to --log_file= as well.
Also if you're wanting to do this with multiple games you can make things easier by making a shortcut without the software's path (default.xex) and dragging the game onto that shortcut.


I also found another bug. If you specify nothing `--log_file=` xenia eventually crashes.
