### ISSUE TITLE
xb devenv error

### ISSUE THREAD

**Issue by strongage** [benvanik/xenia#791]
hey y'all this is my first time using this forum so please be kind,

so I'm trying to run the command xb devenv to run xenia (as you all know that's what it does) but this is the text + error that comes up 

 Launching Visual Studio...

- running premake...
Building configurations...
    Baking capstone...
    Baking gflags...
    Baking glew...
    Baking glslang-spirv...
    Baking imgui...
    Baking libavcodec...
    Baking libavutil...
    Baking snappy...
    Baking spirv-tools...
    Baking vulkan-loader...
    Baking xxhash...
    Baking yaml-cpp...
    Baking xenia-core...
    Baking xenia-app...
    Baking xenia-apu...
    Baking xenia-apu-nop...
    Baking xenia-base...
    Baking xenia-base-tests...
    Baking xenia-cpu...
    Baking xenia-cpu-tests...
    Baking xenia-cpu-ppc-tests...
    Baking xenia-cpu-backend-x64...
    Baking xenia-debug-ui...
    Baking xenia-gpu...
    Baking xenia-gpu-shader-compiler...
    Baking xenia-gpu-null...
    Baking xenia-gpu-gl4...
    Baking xenia-gpu-gl4-trace-viewer...
    Baking xenia-gpu-gl4-trace-dump...
    Baking xenia-gpu-vulkan...
    Baking xenia-gpu-vulkan-trace-viewer...
    Baking xenia-gpu-vulkan-trace-dump...
    Baking xenia-hid...
    Baking xenia-hid-demo...
    Baking xenia-hid-nop...
    Baking xenia-kernel...
    Baking xenia-ui...
    Baking xenia-ui-gl...
    Baking xenia-ui-window-gl-demo...
    Baking xenia-ui-spirv...
    Baking xenia-ui-vulkan...
    Baking xenia-ui-window-vulkan-demo...
    Baking xenia-vfs...
    Baking xenia-apu-xaudio2...
    Baking xenia-hid-winkey...
    Baking xenia-hid-xinput...
Running action 'vs2015'...
Done (1636ms).

- launching devenv...
Traceback (most recent call last):
  File "xenia-build", line 1358, in <module>
    main()
  File "xenia-build", line 87, in main
    return_code = command.execute(args, pass_args, os.getcwd())
  File "xenia-build", line 1350, in execute
    'build\\xenia.sln',
  File "xenia-build", line 200, in shell_call
    subprocess.check_call(command, shell=False, stdout=stdout_file)
  File "C:\python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

I don't know whats wrong as I've literally just started my computing GCSE and we've not done much on coding (probably gonna need to get some prior knowledge though 😄 ) so if anyone knows what to do and could help me I'd be super graetful

many thanks

- strongage

**Comment by maxton** [comment]
Hi strongage, this section is meant for issues with the emulator itself (the code), and is not the place for tech support questions such as these; [the subreddit](https://reddit.com/r/xenia) is more appropriate.

That said I might as well help you

> so I'm trying to run the command xb devenv to run xenia (as you all know that's what it does)

That is not what that command does. `xb devenv` launches Visual Studio with the xenia solution open.

Your problem is that the script is failing to find your Visual Studio installation, so either you don't have VS2015/2017 installed or it is not configured on your path somehow. The latter is very unlikely since the installer does that for you, so I'd say your issue is that you haven't installed Visual Studio.

Make sure you read the docs more carefully because you would have seen on [README.md](https://github.com/benvanik/xenia#quickstart) that `xb devenv` is the command to open Visual Studio. If all you want to do is run Xenia you can download the latest build at [AppVeyor](https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=master&job=Configuration%3A%20Release)
